runtime: nodejs20

service: "default"

# Set resources and scaling
instance_class: F1

# Handlers to serve all files
handlers:
  - url: /.*
    script: auto

# Autoscaling configuration
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_instances: 1  # Ensure a minimum of 1 instance is always running
  max_instances: 10  # Adjust based on your expected traffic

# Environment variables
env_variables:
  NODE_ENV: production
